version: '3.9'
services:
  petto-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT}:3000
    env_file:
      - .env 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - nginx
    networks:
      - petto_network

  petto-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:3000
    depends_on:
      - redis
      - nginx
    volumes:
      - ./backend:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - petto_network
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
    - petto_network

  nginx:
    image: nginx
    ports:
    - 80:80
    - 443:443
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certificate.cer:/etc/ssl/certificate.cer
      - /etc/ssl/private_key.key:/etc/ssl/private_key.key
    
    networks:
      - petto_network


networks:
  petto_network: